name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-pypi

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: false

      - name: Build dist packages
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
